import Head from 'next/head';
import React, { useState } from 'react'
import Layout from '../components/layout';
import TodoForm from '../types/todo-form';

export default function Add() {
  const [form, setForm] = useState<TodoForm>({title: '', description: ''});

  const onSubmit = () => {
    console.log(form);
  };

  const handleChange = (key: any, event: any) => {
    let formValue: any = {...form}
    formValue[key] = event.target.value
    setForm(formValue);
  }

  return (
    <div>
      <Head>
        <title>Add Todo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="" id="main">
        <Layout>
          <div className="px-6 py-2">
            <form name="task-form" action={undefined} onSubmit={onSubmit}>
              <div className="flex flex-col mb-4 text-sm font-medium">
                <span className="mb-1">Title</span>
                <input required={true} type="text" className="border-thin p-2 px-4" placeholder="Title" value={form.title} onChange={e => handleChange("title", e)} />
              </div>
              <div className="flex flex-col mb-4 text-sm font-medium">
                <span className="mb-1">Description</span>
                <textarea className="border-thin p-2 px-4" placeholder="Description" value={form.description} onChange={e => handleChange("description", e)} />
              </div>
              <div>
                <button type="submit" className="p-4 py-2 border-thin text-sm w-full bg-gray-200 hover:bg-white transition-all">Save Task</button>
              </div>
            </form>
            {JSON.stringify(form)}
          </div>
        </Layout>
      </main>
    </div>
  )
}
