import type { NextPage } from 'next';
import Head from 'next/head';
import { AppContext, useAppContext } from '../context/app-context-provider';
import Layout from '../components/layout';
import { useState, useEffect } from 'react';
import BookDetail from '../components/book-detail';
import { Book } from '../types/book';
import { login } from '../services/todo-service';
import TodoList from '../components/todo-list';
import TodoItem from '../types/todo-item';

const items: TodoItem[] = [
  {
    "completed": true,
    "_id": "629a171c3d0a6100175486ce",
    "description": "Reading Book",
    "owner": "6297cd420041ff001759cae6",
    "createdAt": "2022-06-03T14:13:48.521Z",
    "updatedAt": "2022-06-03T14:13:48.521Z",
    "__v": 0
  },
  {
    "completed": false,
    "_id": "629a17ee3d0a6100175486cf",
    "description": "Cleaning Rooms",
    "owner": "6297cd420041ff001759cae6",
    "createdAt": "2022-06-03T14:17:18.004Z",
    "updatedAt": "2022-06-03T14:17:18.004Z",
    "__v": 0
  },
  {
    "completed": false,
    "_id": "629a17ee3d0a6100175486cf",
    "description": "Cleaning Rooms",
    "owner": "6297cd420041ff001759cae6",
    "createdAt": "2022-06-03T14:17:18.004Z",
    "updatedAt": "2022-06-03T14:17:18.004Z",
    "__v": 0
  },
  {
    "completed": false,
    "_id": "629a17ee3d0a6100175486cf",
    "description": "Cleaning Rooms",
    "owner": "6297cd420041ff001759cae6",
    "createdAt": "2022-06-03T14:17:18.004Z",
    "updatedAt": "2022-06-03T14:17:18.004Z",
    "__v": 0
  },
  {
    "completed": false,
    "_id": "629a17ee3d0a6100175486cf",
    "description": "Cleaning Rooms",
    "owner": "6297cd420041ff001759cae6",
    "createdAt": "2022-06-03T14:17:18.004Z",
    "updatedAt": "2022-06-03T14:17:18.004Z",
    "__v": 0
  }
];

const Home: NextPage = () => {
  const [store, dispatch] = useAppContext();
  const [bookDetail, setBookDetail] = useState<Book>();

  const handleBookDetail = (book: Book) => {
    setBookDetail(book);
  };

  const handleClose = () => {
    setBookDetail(undefined);
  };

  const getToken = async () => {
    try {
      let [res] = await login();
      console.log("login", res);
    } catch (e) {
      console.error(e);
    }
  };

  useEffect(() => {
    getToken();
  }, []);


  return (
    <div>
      <Head>
        <title>Barito-do</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="" id="main">
        <Layout>
          <div>
            <TodoList items={items} completed={false} />
          </div>
          <div className="px-6 py-3">Completed Task</div>
          <div>
            <TodoList items={items} completed={true} />
          </div>

        </Layout>
        {bookDetail && <BookDetail book={bookDetail} onClose={handleClose} />}
      </main>
    </div>
  )
}

export default Home
